--
-- Autogenerated SQL script for database schema Project
-- Generated at 2013-04-25T22:38:13
-- Knightrunner.Library.Database.Schema.SqlServer.SqlServerScriptGenerator, Knightrunner.Library.Database.Schema.SqlServer, Version=1.1.0.0, Culture=neutral, PublicKeyToken=8edf591bb966d98e

CREATE TABLE [dbo].[Users]
(
	[Id] Bigint IDENTITY NOT NULL,
	[PublicId] NVarChar(255) NOT NULL,
	[Active] Bit NOT NULL
);

ALTER TABLE [dbo].[Users] ADD CONSTRAINT [Users_pk] PRIMARY KEY CLUSTERED
([Id]);

CREATE UNIQUE INDEX [UsersPublicId_ux] ON [dbo].[Users]
([PublicId]);

GO

CREATE TABLE [dbo].[Projects]
(
	[Id] Bigint IDENTITY NOT NULL,
	[PublicId] NVarChar(255) NOT NULL,
	[ParentId] Bigint,
	[Text] NVarChar(2000) NOT NULL,
	[Active] Bit NOT NULL
);

ALTER TABLE [dbo].[Projects] ADD CONSTRAINT [Projects_pk] PRIMARY KEY CLUSTERED
([Id]);

CREATE UNIQUE INDEX [ProjectPublicId_ux] ON [dbo].[Projects]
([PublicId]);

GO

CREATE TABLE [dbo].[ActivityTypes]
(
	[Id] Bigint IDENTITY NOT NULL,
	[PublicId] NVarChar(255) NOT NULL,
	[Text] NVarChar(2000) NOT NULL,
	[Active] Bit NOT NULL
);

ALTER TABLE [dbo].[ActivityTypes] ADD CONSTRAINT [ActivityTypes_pk] PRIMARY KEY CLUSTERED
([Id]);

CREATE UNIQUE INDEX [ActivityTypePublicId_ux] ON [dbo].[ActivityTypes]
([PublicId]);

GO

CREATE TABLE [dbo].[Activities]
(
	[Id] Bigint IDENTITY NOT NULL,
	[UserId] Bigint NOT NULL,
	[ProjectId] Bigint,
	[ActivityTypeId] Bigint,
	[Start] DateTime NOT NULL,
	[Duration] Int,
	[Text] NVarChar(2000)
);

ALTER TABLE [dbo].[Activities] ADD CONSTRAINT [Activities_pk] PRIMARY KEY CLUSTERED
([Id]);

CREATE INDEX [ActivitiesUserStart_ix] ON [dbo].[Activities]
([UserId], [Start]);

GO

CREATE TABLE [dbo].[JournalEntries]
(
	[Id] Bigint IDENTITY NOT NULL,
	[UserId] Bigint NOT NULL,
	[DateTime] DateTime NOT NULL,
	[Type] SmallInt NOT NULL,
	[TypeOrigin] SmallInt NOT NULL,
	[Text] NVarChar(2000)
);

ALTER TABLE [dbo].[JournalEntries] ADD CONSTRAINT [JournalEntries_pk] PRIMARY KEY CLUSTERED
([Id]);

CREATE INDEX [JournalEntriesUserDate_ix] ON [dbo].[JournalEntries]
([UserId], [DateTime]);

GO

CREATE TABLE [dbo].[Reminders]
(
	[Id] Bigint IDENTITY NOT NULL,
	[UserId] Bigint NOT NULL,
	[Text] NVarChar(2000),
	[Active] Bit NOT NULL,
	[ValidFrom] DateTime NOT NULL,
	[Seconds] NVarChar(50) NOT NULL,
	[Minutes] NVarChar(50) NOT NULL,
	[Hours] NVarChar(50) NOT NULL,
	[Months] NVarChar(50) NOT NULL,
	[DaysOfMonth] NVarChar(50) NOT NULL,
	[DaysOfWeek] NVarChar(50) NOT NULL,
	[Years] NVarChar(50) NOT NULL
);

ALTER TABLE [dbo].[Reminders] ADD CONSTRAINT [Reminders_pk] PRIMARY KEY CLUSTERED
([Id]);

GO

GO

ALTER TABLE [dbo].[Projects] WITH CHECK ADD CONSTRAINT [ProjectsParent_fk] FOREIGN KEY
([ParentId]) REFERENCES [dbo].[Projects] ([Id]);
GO

GO

ALTER TABLE [dbo].[Activities] WITH CHECK ADD CONSTRAINT [Activities_UserId_fk] FOREIGN KEY
([UserId]) REFERENCES [dbo].[Users] ([Id]);
ALTER TABLE [dbo].[Activities] WITH CHECK ADD CONSTRAINT [Activities_ProjectId_fk] FOREIGN KEY
([ProjectId]) REFERENCES [dbo].[Projects] ([Id]);
ALTER TABLE [dbo].[Activities] WITH CHECK ADD CONSTRAINT [Activities_ActivityTypeId_fk] FOREIGN KEY
([ActivityTypeId]) REFERENCES [dbo].[ActivityTypes] ([Id]);
GO

ALTER TABLE [dbo].[JournalEntries] WITH CHECK ADD CONSTRAINT [JournalEntries_UserId_fk] FOREIGN KEY
([UserId]) REFERENCES [dbo].[Users] ([Id]);
GO

ALTER TABLE [dbo].[Reminders] WITH CHECK ADD CONSTRAINT [Reminders_UserId_fk] FOREIGN KEY
([UserId]) REFERENCES [dbo].[Users] ([Id]);
GO

