//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Datetime:2013-06-02T14:37:37
//     Runtime Version:4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using PetaPoco;

namespace Knightrunner.WorkTrack2013.Database.Entities
{
	[TableName(_Names._Table)]
	[PrimaryKey(_Names.Id, autoIncrement = true)]
	public partial class Activity
	{
		public static class _Names
		{
			public const string _Table = "dbo.Activities";
			public const string Id = "Id";
			public const string UserId = "UserId";
			public const string ProjectId = "ProjectId";
			public const string ActivityTypeId = "ActivityTypeId";
			public const string Start = "Start";
			public const string DurationSeconds = "DurationSeconds";
			public const string Text = "Text";
		}

		[Column(_Names.Id)]
		public long Id { get; set; }
		[Column(_Names.UserId)]
		public long UserId { get; set; }
		[Column(_Names.ProjectId)]
		public long? ProjectId { get; set; }
		[Column(_Names.ActivityTypeId)]
		public long? ActivityTypeId { get; set; }
		[Column(_Names.Start)]
		public System.DateTime Start { get; set; }
		[Column(_Names.DurationSeconds)]
		public int? DurationSeconds { get; set; }
		[Column(_Names.Text)]
		public string Text { get; set; }
	}
}

