//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Datetime:2013-06-02T14:37:37
//     Runtime Version:4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using PetaPoco;

namespace Knightrunner.WorkTrack2013.Database.Entities
{
	[TableName(_Names._Table)]
	[PrimaryKey(_Names.Id, autoIncrement = true)]
	public partial class JournalEntry
	{
		public static class _Names
		{
			public const string _Table = "dbo.JournalEntries";
			public const string Id = "Id";
			public const string UserId = "UserId";
			public const string DateTime = "DateTime";
			public const string Type = "Type";
			public const string TypeOrigin = "TypeOrigin";
			public const string Text = "Text";
		}

		[Column(_Names.Id)]
		public long Id { get; set; }
		[Column(_Names.UserId)]
		public long UserId { get; set; }
		[Column(_Names.DateTime)]
		public System.DateTime DateTime { get; set; }
		[Column(_Names.Type)]
		public int Type { get; set; }
		[Column(_Names.TypeOrigin)]
		public int TypeOrigin { get; set; }
		[Column(_Names.Text)]
		public string Text { get; set; }
	}
}

