//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Datetime:2013-04-25T22:38:13
//     Runtime Version:4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using PetaPoco;

namespace Knightrunner.WorkTrack2013.Database.Entities
{
	[TableName("dbo.JournalEntries")]
	[PrimaryKey("Id", autoIncrement = true)]
	public partial class JournalEntry
	{
		[Column("Id")]
		public long Id { get; set; }
		[Column("UserId")]
		public long UserId { get; set; }
		[Column("DateTime")]
		public System.DateTime DateTime { get; set; }
		[Column("Type")]
		public int Type { get; set; }
		[Column("TypeOrigin")]
		public int TypeOrigin { get; set; }
		[Column("Text")]
		public string Text { get; set; }
	}
}

