//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Datetime:2013-06-02T14:37:37
//     Runtime Version:4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using PetaPoco;

namespace Knightrunner.WorkTrack2013.Database.Entities
{
	[TableName(_Names._Table)]
	[PrimaryKey(_Names.Id, autoIncrement = true)]
	public partial class Reminder
	{
		public static class _Names
		{
			public const string _Table = "dbo.Reminders";
			public const string Id = "Id";
			public const string UserId = "UserId";
			public const string Text = "Text";
			public const string Active = "Active";
			public const string ValidFrom = "ValidFrom";
			public const string Seconds = "Seconds";
			public const string Minutes = "Minutes";
			public const string Hours = "Hours";
			public const string Months = "Months";
			public const string DaysOfMonth = "DaysOfMonth";
			public const string DaysOfWeek = "DaysOfWeek";
			public const string Years = "Years";
		}

		[Column(_Names.Id)]
		public long Id { get; set; }
		[Column(_Names.UserId)]
		public long UserId { get; set; }
		[Column(_Names.Text)]
		public string Text { get; set; }
		[Column(_Names.Active)]
		public bool Active { get; set; }
		[Column(_Names.ValidFrom)]
		public System.DateTime ValidFrom { get; set; }
		[Column(_Names.Seconds)]
		public string Seconds { get; set; }
		[Column(_Names.Minutes)]
		public string Minutes { get; set; }
		[Column(_Names.Hours)]
		public string Hours { get; set; }
		[Column(_Names.Months)]
		public string Months { get; set; }
		[Column(_Names.DaysOfMonth)]
		public string DaysOfMonth { get; set; }
		[Column(_Names.DaysOfWeek)]
		public string DaysOfWeek { get; set; }
		[Column(_Names.Years)]
		public string Years { get; set; }
	}
}

