//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Datetime:2013-04-25T22:38:13
//     Runtime Version:4.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using PetaPoco;

namespace Knightrunner.WorkTrack2013.Database.Entities
{
	[TableName("dbo.Reminders")]
	[PrimaryKey("Id", autoIncrement = true)]
	public partial class Reminder
	{
		[Column("Id")]
		public long Id { get; set; }
		[Column("UserId")]
		public long UserId { get; set; }
		[Column("Text")]
		public string Text { get; set; }
		[Column("Active")]
		public bool Active { get; set; }
		[Column("ValidFrom")]
		public System.DateTime ValidFrom { get; set; }
		[Column("Seconds")]
		public string Seconds { get; set; }
		[Column("Minutes")]
		public string Minutes { get; set; }
		[Column("Hours")]
		public string Hours { get; set; }
		[Column("Months")]
		public string Months { get; set; }
		[Column("DaysOfMonth")]
		public string DaysOfMonth { get; set; }
		[Column("DaysOfWeek")]
		public string DaysOfWeek { get; set; }
		[Column("Years")]
		public string Years { get; set; }
	}
}

